### ISSUE TITLE
Conversions class

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/ingraph#106]
There are two source files for the same class:
* https://github.com/FTSRG/ingraph/blob/0321b8895c723e3585549ecf443913f006a3bf6e/ingraph-ire/src/main/scala/ingraph/ire/Conversions.scala
* https://github.com/FTSRG/ingraph/blob/a79c76c7e6060bffe0cc9cf7e0116b10ff422420/ingraph-expression-parser/src/main/scala/ingraph/expressionparser/Conversions.scala

We should remove duplication and rename the class to something more descriptive, e.g. `EmfConversions`

**Comment by wafle** [comment]
It also contains guava conversion, so i haven't renamed it.
