### ISSUE TITLE
Handle contradicting edge label constraints in optimizer

### ISSUE THREAD

**Issue by jmarton** [FTSRG/ingraph#121]
Follow-up task from #11 : handle contradicting edge label constraint in the optimizer

Combination of labelset constraints might result in being non-satisfiable
(false, also known as contradicting).

E.g. for the same edge variable edge1, the following labelset constraints were given in the query:

 1. `[edge1:A|B]`, so edge1 needs to have either label A, either label B
 2. `[edge1:C]`, so edge1 needs to have label C.

These are contradicting as a single edge instance can have at most one label.

**Comment by szarnyasg** [comment]
Actually, this is totally not important. Our users should start with well-specified queries :-). Closing this.
