### ISSUE TITLE
Implement toString() methods for operators and expressions

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/ingraph#122]
This would help debugging a lot. Xcore supports the `toString()` method, so this can be done quite easily.

**Comment by szarnyasg** [comment]
We will also use these for equality checking, e.g. finding common attributes for joins.

**Comment by szarnyasg** [comment]
We are already using this for variables quite extensively.

**Comment by szarnyasg** [comment]
This was not really required in the last couple of weeks, so closing this as wontfix for now.

**Comment by imbur** [comment]
This would indeed help a lot debugging search-based execution plans. Reopening this issue.

**Comment by szarnyasg** [comment]
We get this out-of-the-box with Catalyst, so closing this as "wontfix".
