### ISSUE TITLE
Projection arguments in the elements list not serialized

### ISSUE THREAD

**Issue by jmarton** [FTSRG/ingraph#130]
When running  `ingraph.cypher2relalg.trainbenchmark.TrainBenchmarkCypher2Relalg2TexTest.testPosLength()`, projection lacks projected ExpressionVariables.

It seems to be caused by the fact that `GroupingProjectionOperatorConverter.projectionOperator` does not serialize the elements which were filled in by the compiler. Instead it serializes `otherFunctions` and `aggregations` attributes of the `ProjectionOperator` object, that are not handled by the compiler.

**Comment by szarnyasg** [comment]
I think we should wait with the fix for #127.

**Comment by szarnyasg** [comment]
This was somehow fixed along the way! =)

**Comment by jmarton** [comment]
Done in e5c2421aa22101ce153183e4c15926c816a3d265.
