### ISSUE TITLE
Aggregation operations should not be performed by the Projection operator

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/ingraph#132]
We should compile the [aggregation functions](https://neo4j.com/docs/developer-manual/3.0/cypher/#query-functions-aggregating) to the aggregation operator instead of the projection operator.

See also:
* a CIR submitted today for openCypher: https://github.com/thobe/openCypher/blob/19c6bade43cca732bf736166fcad4effc29b1afc/cip/1.accepted/CIP2017-04-13-Aggregations.adoc
* Ullman's grouping operator in http://infolab.stanford.edu/~ullman/fcdb/slides/slides5.pdf, p21

**Comment by szarnyasg** [comment]
See also #127.

**Comment by szarnyasg** [comment]
I thought about this a bit and I think we can do this without #127. That issue will not be decided before OCIM2, while this issue should be resolved in the ADBIS paper (i.e. we should _not_ treat aggregations as functions, but as separate operations).

Defining aggregations as a function had the nice side-effect that we could easily translate stuff like `count(x)+1` or even `sum(n.age+2)` (I don't know if the latter ever worked, but it was theoretically possible).

With a separate [grouping operator](http://courses.cs.vt.edu/~cs4604/Fall09/lectures/lecture-07-bags-versus-sets.pdf#page=46), the `+1`/`+2` operations should still be performed by a projection operator that succeeds/precedes the grouping operator (respectively).

**Comment by szarnyasg** [comment]
My first idea was to move the aggregation functions from the [`Function`](https://github.com/FTSRG/ingraph/blob/d70c57d97eac7f40afb816ff0b43f5186ac764b3/ingraph-relalg-model/src/main/java/relalg/function/Function.java) enumeration to a separate [`Aggregation`] enumeration.

However, until the [related CIP](https://github.com/thobe/openCypher/blob/19c6bade43cca732bf736166fcad4effc29b1afc/cip/1.accepted/CIP2017-04-13-Aggregations.adoc) is introduced to the grammar, aggregation is still implemented as a [`FunctionInvocation`](https://github.com/slizaa/slizaa-opencypher-xtext/blob/master/plugins/org.slizaa.neo4j.opencypher/src/org/slizaa/neo4j/opencypher/OpenCypher.xtext#L718). Currently, this is [translated like this](https://github.com/FTSRG/ingraph/blob/d70c57d97eac7f40afb816ff0b43f5186ac764b3/ingraph-cypher2relalg/src/main/java/ingraph/cypher2relalg/RelalgBuilder.xtend#L1176):

```java
def void populateFunctionExpression(FunctionExpression fe, FunctionInvocation fi) {
	fe.functor = Function.valueOf(fi.functionName.name.toUpperCase)
	// use of lazy map OK as wrapped into addAll - jmarton, 2017-01-07
	fe.arguments.addAll(fi.parameter.map[buildRelalgExpression(it)])
}
```

For this reason, it might be beneficial to keep aggregations in the function class for now and post-process aggregation functions in the RelalgBuilder (i.e. introduce the aggregation operation in the corresponding GroupingOperator).

**Comment by jmarton** [comment]
@szarnyasg pls comment on the current state:

Query:

```
MATCH (segment:Segment)
WHERE segment.length <= 0
RETURN DISTINCT segment.length AS length, count(*) as cs
```

Visualized relational graph algebra tree. The `\gamma` operator shows grouping criteria in superscript, while subscript is the list of output expressions.

![grouping](https://cloud.githubusercontent.com/assets/10688599/25249727/3705b00a-2613-11e7-9d52-654db4fcbac1.png)

**Comment by szarnyasg** [comment]
I like this so far.

> If ProjectionOperator was the renaissance man, this is Baroque of the relational graph algebra model.

:D
