### ISSUE TITLE
Query compilation error

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/ingraph#137]
The following query does not compile perfectly:
```
MATCH (m1:Message)
WITH m1.language AS singleLang, count(*) AS cnt
WHERE cnt = 1
MATCH (m2:Message)
WHERE m2.language = singleLang
OPTIONAL MATCH (m2)-[:REPLY_OF]->(m3:Message)
RETURN m2.language as replyLang, m3.language as originalLang
```

**Comment by szarnyasg** [comment]
This introduced a StackOverflowError in the extractContainer method:

![image](https://cloud.githubusercontent.com/assets/1402801/25656592/0cd968ee-2ffa-11e7-92f7-3e2002e2a81d.png)

**Comment by jmarton** [comment]
Problem skipped in 2846b71ca66e20fd7c9683cbda69b62d70a7a465. Further investigation is to be done in #140
