### ISSUE TITLE
Implement DualObjectSourceOperator

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/ingraph#139]
This is required by bi/query-6.

The DualObjectSourceOperator (**edit:** operator name) is a nullary operator that returns a ~single tuple with a single NULL value~ a single empty tuple. It is commonly used as the left input of a left outer join.

**Comment by jmarton** [comment]
The tuple emitted by the DualOperator should be a zero-element tuple, so it should not hold a NULL value, and its schema should be the empty list.

**Comment by wafle** [comment]
Done via 4fbc16f.
