### ISSUE TITLE
Aggregation after WITH

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/ingraph#141]
We were inspecting SNB BI query 13 with @wafle and stumbled upon this.

```
MATCH (message:Message)-[:hasTag]->(tag:Tag)
RETURN message, count(tag) AS tags
```
![image](https://cloud.githubusercontent.com/assets/1402801/25672340/65f9f77a-3033-11e7-9962-18268245911d.png)

If we add `WITH message, tag`, which should not have any effect on the query results, the aggregation criteria (`messenger`) will be missing from the grouping operator.

```
MATCH (message:Message)-[:hasTag]->(tag:Tag)
WITH message, tag
RETURN message, count(tag) AS tags
```
![image](https://cloud.githubusercontent.com/assets/1402801/25672331/5ee4ba60-3033-11e7-830d-c50fe4c0af46.png)

I think this is not correct - can you please check this?

**Comment by jmarton** [comment]
@szarnyasg This seems to be caused by 536d422ecc71f16dc1914552ec6ddcf16d4c7230, for which currently I don't understand the motivation clearly. Needs some investigation.
