### ISSUE TITLE
Queries starting with OPTIONAL MATCH

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/ingraph#142]
The query plan generated from the following query does not contain any Dual operators:

```
OPTIONAL MATCH (n)
RETURN n
```

**Comment by jmarton** [comment]
@szarnyasg according to my tests, b1039f2cb6186d710b702c0ca85342a9894313c1 contains the `dual` as shown below. Please double check.

![optional-match-compiled](https://cloud.githubusercontent.com/assets/10688599/25717968/9c6605f2-3104-11e7-8a0d-449af9d8c148.png)

**Comment by szarnyasg** [comment]
Corrent - my visualizer also performed the simplifying transformations and derived this:

![image](https://cloud.githubusercontent.com/assets/1402801/25718302/d0357a9c-3105-11e7-9ea3-e7476f6d8d16.png)

**Comment by szarnyasg** [comment]
This means that the issue is in the transformations. I'll fix it in a sec.
