### ISSUE TITLE
Booleans should be comparable with equality and inequality

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/ingraph#145]
BooleanLiteral is not Comparable.

`RETURN true>false` does not work, but `RETURN true=false` should compile.

**Comment by szarnyasg** [comment]
@jmarton is this still an issue with the Catalyst model?

**Comment by jmarton** [comment]
@szarnyasg in fact the Catalyst expression model is not statically typed. Rather it has some way to infer the type of the expressions. During this inference step, if some expressions turn out to be incompatible with its parent operator, an error condition should be raised. (I'm not sure about how and where to implement this, but basically this is the idea.)

**Comment by szarnyasg** [comment]
Due to static typing, it would be difficult to check for this issue. I think it's okay if the engine throws an exception during runtime for these cases.
