### ISSUE TITLE
IntegerLiteral and BigIntegerLiteral but no literal for Longs

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/ingraph#148]
We have IntegerLiteral and BigIntegerLiteral but no LongLiterals. Number between 2^32 and 2^64 (or numbers smaller than 2^64) are usually treated as longs - is there a reason we did not keep this?

**Comment by jmarton** [comment]
Either

1. we could make IntegerLiteral to store a long value, or
2. we could extend a model to represent long in a separate way.

Option (2) would make the model and code more complex. Option (1) should not have bad performance impact on nowdays' computers and keeps the relalg model and code base simple.

I'd vote for option (1).

**Comment by szarnyasg** [comment]
I agree with (1).

**Comment by wafle** [comment]
I vote for (2). Why is handling numbers with an L at the end more complex than handling floats for example?
It does have a performance impact, in fact that's why JVMs slow down when going beyond 32 gigs of memory.

**Comment by szarnyasg** [comment]
> It does have a performance impact, in fact that's why JVMs slow down when going beyond 32 gigs of memory.
AFAIK this is mostly caused by garbage collection issues. How is this related to ints vs longs?

**Comment by wafle** [comment]
With 8 byte pointer boundaries you can keep track of 32 gigs of memory using 32 bit pointers:
https://www.elastic.co/guide/en/elasticsearch/guide/2.x/heap-sizing.html#compressed_oops

Neo4j also uses longs as [IntegerLiterals](https://github.com/neo4j/neo4j/blob/0d953c737775b3dc5320ce3287c015cb0df12ddb/community/cypher/frontend-3.3/src/main/scala/org/neo4j/cypher/internal/frontend/v3_3/ast/Literal.scala#L36), with that in mind, (1) is probably a better option.

**Comment by szarnyasg** [comment]
> Once you cross that magical ~32 GB boundary, the pointers switch back to ordinary object pointers. The size of each pointer grows, more CPU-memory bandwidth is used, and you effectively lose memory. In fact, it takes until around 40–50 GB of allocated heap before you have the same effective memory of a heap just under 32 GB using compressed oops.
> 
> The moral of the story is this: even when you have memory to spare, try to avoid crossing the 32 GB heap boundary. It wastes memory, reduces CPU performance, and makes the GC struggle with large heaps.

It's a good thing ingraph is going to be a distributed engine... eventually :-)

**Comment by jmarton** [comment]
For (1): arithmetic operations on primitive 32-bit and 64 bit integer values on 64bit CPUs should take the same time if we don't take into account superscalar-optimizations.

In fact, JVM might do some out-of-order, superscalar optimizations, see e.g. [10.1109/IWIA.2005.44](https://doi.org/10.1109/IWIA.2005.44), but as soon as we are there to measure this as a bottleneck we still can move on to opt (2).
