### ISSUE TITLE
Queries starting with the "WITH" keyword

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/ingraph#149]
Both queries compile, but the second one give a bad result:

```
WITH [1, 2] AS xs
UNWIND xs AS x
RETURN x
```

![image](https://cloud.githubusercontent.com/assets/1402801/26576535/8194b51e-4529-11e7-8c7f-5f594ea9360c.png)

```
UNWIND [1, 2] AS x
RETURN x
```

![image](https://cloud.githubusercontent.com/assets/1402801/26576552/8f5ad6ce-4529-11e7-94e3-840f7835703a.png)

**Comment by jmarton** [comment]
This has been a serialization problem, the relalg search model has already referenced the list literal.

This is the non-transformed compiled form for the 2nd query:

```
UNWIND [1, 2] AS x
RETURN x
```

![direct-unwind](https://cloud.githubusercontent.com/assets/10688599/26580249/92dd5ec6-4537-11e7-8055-30d26f0f8745.png)
