### ISSUE TITLE
GetEdgesOperator extends NavigationDescriptor

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/ingraph#157]
The `GetEdgesOperator` contains an `AbstractEdgeVariable`, but it only supports `EdgeVariable`s - and it does not support `EdgeListVariable`s.

**Comment by jmarton** [comment]
Actually, what do we use the `GetEdgesOperator` for? Compiler currently never puts it in the tree.

On the other hand, if we use it for optimization purposes to replace a `GetVerticesOperator` and an `ExpandOperator`, then it might be beneficial to also support `EdgeListVariable`s. Or we might place a runtime resctriction telling that `GetEdgesOperator.edgeVariable` always holds an `EdgeVariable` instance.

**Comment by szarnyasg** [comment]
The Rete representation uses it, see here: https://github.com/FTSRG/ingraph/blob/c8cac319dc0356ff5b721d2f69f4414a396e9556/ingraph-compiler/ingraph-compiler-transformations/src/main/java/ingraph/optimization/transformations/AbstractRelalgTransformation.xtend#L109

**Comment by szarnyasg** [comment]
This is still done in the Scala / Catalyst implementation: https://github.com/FTSRG/ingraph/blob/0365819768e8a905020118eb30a7ab34df4a91ee/compiler/src/main/scala/ingraph/model/iplan.scala#L32
