### ISSUE TITLE
Rename relalg-search-rete models

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/ingraph#158]
cc @szdavid92 

We had a discussion with @imbur today and concluded that the current naming is quite confusing as the `search` model (built by the `RelalgBuilder` class) does not define an actual search plan. We propose the following names:

* `relalg` (formerly _search_) for non-incremental plans,
* `rete` (formerly _rete_) for incremental plans,
* `queryplan` (formerly _relalg_) for the common model of `relalg` and `rete` models (defined in the `queryplan.xcore` file).

@jmarton what do you think?

**Comment by wafle** [comment]
I'd prefer calling them ((Non)?Incremental)?QueryPlan. If you have to explain what the name means it's not a very good name.

**Comment by szarnyasg** [comment]
Well, good point, but then we'd have other lousy class names like `NonIncremental2IncrementalQueryPlanTransformation`. I think all (current and future) ingraph developers are well aware what Rete is, so we can safely use that term in the code - let's see what others think on this.

**Comment by szarnyasg** [comment]
A point against incremental and nonincremental - they have the same postfix which makes it more difficult to search for them.

**Comment by jmarton** [comment]
I think that refacoring of metamodels is much more important than the naming. We should separate the common base, the metamodel for the non-incremental plan and for the incremental plan, i.e. create 3 `xcore` files.

An other point is that rete is an implementation detail (which is unlikely to change, though), so I'd avoid to call it as such.

For the naming: as also the operators in the incremental plan encapsulates graph relational algebraic operators, I'd propose the following:

 - `relalg` for the common base, optionally factoring out data structures (variables) and expressions to a separate, parent model
 - `queryplan` (or `qplan`) for the non-incremental plan, which is the traditional approach
 - `iplan` for the incremental plan

**Comment by szarnyasg** [comment]
As we are moving to Catalsyt, we should get back to this issue and get the names right on this occassion :-).

**Comment by szarnyasg** [comment]
Moving to Catalyst resolved this.
