### ISSUE TITLE
Indexer doesn't support multiple edges with the same label

### ISSUE THREAD

**Issue by szdavid92** [FTSRG/ingraph#160]
The edges are stored in a way that doesn't allow for a label to point to multiple edges. See the [Indexer](https://github.com/FTSRG/ingraph/blob/master/ingraph-engine/ingraph-engine-ingraph-ire/src/main/scala/ingraph/ire/Indexer.scala#L15)

**Comment by wafle** [comment]
I don't have time to fix it this week, but it can be solved by switching to buffer multimap.
