### ISSUE TITLE
Compilation of positive/negative patterns in WHERE

### ISSUE THREAD

**Issue by jmarton** [FTSRG/ingraph#162]
SDL/3 query revealed that variables that join the (negative) pattern in the WHERE clause to the patterns of the match should not have a `NOT NULL` constraint.

What's more: we should think of the compilation of pattern conditions.

**Comment by jmarton** [comment]
Not a bug: adding the mentioned `NOT NULL` filter condition is redundant, but logically the compilation is OK.

Discussion about compiling pattern conditions remains open.

**Comment by szarnyasg** [comment]
This is resolved as part of #234.
