### ISSUE TITLE
Relation algebra generated model classes can return null for toString

### ISSUE THREAD

**Issue by szdavid92** [FTSRG/ingraph#167]
Several tools, like the Scala REPL, and Scala Worksheet is rendered unusable when faced with a `null` in place of a String.

```
scala> :paste
// Entering paste mode (ctrl-D to finish)

val v = new Object {
  override def toString = null
}

// Exiting paste mode, now interpreting.

java.lang.NullPointerException
  at scala.runtime.ScalaRunTime$.replStringOf(ScalaRunTime.scala:264)
  at .$print$lzycompute(<console>:10)
  at .$print(<console>:6)
  at $print(<console>)
```

Also other tools that handle this, they usually write the string `"null"` into the output which is very misleading, as it is very easy to interpret it as the whole thing is a `null`.

![image](https://user-images.githubusercontent.com/5807322/27656909-1dd4c80a-5c4b-11e7-9b12-f46c64cb8165.png)

What about this e.g 
```
VariableExpression { myVariable }
VariableExpression { null }
```
Or
```
VariableExpression { name: myVariable }
```
which is more verbose?

**Comment by szdavid92** [comment]
I made a fix to avoid the errors, but didn't care about the formatting, so we should revise this. #166

**Comment by szarnyasg** [comment]
See b6f0e17ccd393eaf310bbb7b02a67de2b350f7e1 on my take.
