### ISSUE TITLE
Make variable scoping explicit

### ISSUE THREAD

**Issue by szdavid92** [FTSRG/ingraph#169]
Currently if we have a query where variables with the same name live under different scopes, the only way to effectively differentiate between them is to use an reference equality check.

This makes the model hard to port, as this is a technology dependent operation.

E.g.
```
MATCH (v)-->(x)
WITH x
MATCH (v)-->(y)
RETURN x, y
```

will be mapped to two `v` objects with the same properties:

![image](https://user-images.githubusercontent.com/5807322/27690106-a95f63f4-5ce0-11e7-9701-ddba41a93680.png)

**Comment by jmarton** [comment]
Once #284 is merged, this will be done.

Using the `ingraph.model.expr.ResolvableName` trait, vertex, edge, edgelist and property attributes as well as ReturnItems get resolved in the QPlan stage to a unique name.

In the above example, name resolution results in the following:

```
MATCH (v)-->(x)  // v#0, x#0
WITH x           // x#0
MATCH (v)-->(y)  // v#1, y#0
RETURN x, y      // x#0, y#0
```

**Comment by jmarton** [comment]
#284 was merged, so this is done.
