### ISSUE TITLE
AllDifferent should accept variables and set of variables as well

### ISSUE THREAD

**Issue by jmarton** [FTSRG/ingraph#17]
To facilitate range edge queries, AllDifferent operator should accept edge-variables and edge list variables. On the resultset the flattened union should be tested for pairwise inequality.
- [x] modify EMF model
- [x] extend expand operator to have edge list variables

**Comment by szarnyasg** [comment]
Just stumbled upon this - currently both the `edgeVariables` and the `edgeVariableSets` attributes of the AllDifferent operator are always empty.

**Comment by wafle** [comment]
Any progress on this? It seems like it causes issues with the LDBC BI queries.
