### ISSUE TITLE
Bugous unwrapping when serializing a variableexpression

### ISSUE THREAD

**Issue by jmarton** [FTSRG/ingraph#180]
86db0c607ad598df3e578ea7330a9c3c0e909326 introduced unwrapping of a VariableExpression when displaying aliases, i.e. for the query:

```
MATCH (s)
RETURN s as g
```

We receive the following when visualized:

![alias_name_issue](https://user-images.githubusercontent.com/10688599/28072220-a9b6224a-6652-11e7-9afe-639954e06e65.png)

**Comment by jmarton** [comment]
@szarnyasg why do we do this?

**Comment by szarnyasg** [comment]
Well, I'm not sure. My only guess, based on the commit msg, is that it caused a SO error somewhere.

**Comment by szarnyasg** [comment]
I think moving to Catalyst made this issue deprecated, so I'm closing it.
