### ISSUE TITLE
Simplify project names

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/ingraph#183]
As suggested by @szdavid92, we should simplify project names, i.e. ingraph-engine:ingraph-engine-driver should become ingraph-engine:driver, etc.

**Comment by szdavid92** [comment]
why not simply engine:driver?

**Comment by szarnyasg** [comment]
the groupId (ingraph-engine or engine) has to be unique

**Comment by szarnyasg** [comment]
This is done on the `master` branch.
