### ISSUE TITLE
Create indexer method that returns vertices for the given label set

### ISSUE THREAD

**Issue by szdavid92** [FTSRG/ingraph#184]
The indexer is only capable of returning vertices for a single label. However it would be useful to return vertices based on multi label criteria.

I propose adding a
```scala
def getVerticesByLabelSet(labelSet: Set[String]): Seq[Vertex]
```

operation to the indexer.

**Comment by jmarton** [comment]
We do have `VertexLabelSet` in the `relalg.xcore` model, which might also be used here.

**Comment by szarnyasg** [comment]
https://github.com/FTSRG/ingraph/blob/3e027a7f60371b0443520ece709605a4a08d0b07/compiler/src/main/scala/ingraph/model/expr.scala#L82

**Comment by szarnyasg** [comment]
https://github.com/FTSRG/ingraph/blob/88039a1f04ae212ce959d544955b6f1dcef6f4c2/indexer/src/main/scala/ingraph/ire/Indexer.scala#L131 does this.
