### ISSUE TITLE
Compile functions for the Catalyst-based relalg model

### ISSUE THREAD

**Issue by jmarton** [FTSRG/ingraph#206]
- [x] compile to unresolved function
- [ ] resolve function calls

**Comment by jmarton** [comment]
function resolution was first implemented in e0146acd356f0b417ce61dae9856fdb3980c02d0

**Comment by szarnyasg** [comment]
Should this comment be removed? https://github.com/FTSRG/ingraph/blob/f2a1e6bb0a5e8f529346d2af439eec1d603ceaa0/compiler/src/main/scala/ingraph/compiler/cypher2gplan/builders/ExpressionBuilder.scala#L36

**Comment by jmarton** [comment]
Done. Thx @szarnyasg for raising this.
