### ISSUE TITLE
HasLabels constraints should refer to a set?

### ISSUE THREAD

**Issue by szdavid92** [FTSRG/ingraph#210]
The HasLabels constraints is really a 'HasLabel' constraint in a sense you can only specify one label at a time. Ideally we could specify a set of labels, without complicating the task.

However this would require checking for a set of constraints as a primitive operation, concretely GetVerticesByLabel should be able to retrieve a vertex for a set of labels, otherwise changing the constraint creates an inconsistency. (Supposing we don't work around it by adding additional checks as filters to the task.) So I see 3 ways:

- don't do anything -> we will need as many constraints as labels
- change variable to a set -> we should make sure that all operations remain consistent and primitive, so their cost is easier to reason about.
- introduce new constraint type, so we can talk about a single label or a set -> maximum flexibility. but may also need rule based constraint transformations.

I thought about these rule based  transformations and they might be possible to integrate into our cost based operation planner. Currently what I am thinking about is instead of simply moving a constraint from free to bound when selecting an applicable op, it can create other arbitrary bound and free constraints as part of the transformation.

E.g

GetVerticesByLabel -> can transform a 
```
free
------
HasLabels(v, l)
Vertex (v)
```
and output

```
free 
HasLabels(v, l_1) <--- A set with removed label that can be checked by the indexer as part of the vertex retrieval operation
bound
Vertex(v)
HasLabel(v, l_0) <---- the sole label that is checked by the op
```

But because it splits variables it smells a bit. There should be really an abstraction for constants, this virtual variable thing is strange here.
Also multiple transformations for an operation need to be supported for this, becuase now GetVerticesByLabel should be able to handle the current configuration as well (when it binds a single HasLabel and Vertex thing).

**Comment by szarnyasg** [comment]
@szdavid92 any updates on this? Did you find a suitable solution?

**Comment by szdavid92** [comment]
not yet
