### ISSUE TITLE
Full support for properties

### ISSUE THREAD

**Issue by szdavid92** [FTSRG/ingraph#219]
Currently, properties are [stored in simple key-value map](https://github.com/FTSRG/ingraph/blob/master/indexer/src/main/scala/ingraph/ire/Indexer.scala#L13), limiting IngraphElement capabilities to that of a single level associative container. In order to fully implement openCypher queries we need [nested properties](https://s3.amazonaws.com/artifacts.opencypher.org/railroad/Expression.html).

Seems like an arbitrary amount of PropertyLookups can come before appending an arbitrary amount of bracketed expressions, on which even subsetting is supported.

**Comment by wafle** [comment]
This is techinaclly not a limitation of the indexer. You can cast Any to a Map[String, Any] when you use it, i.e. not in the indexer.

**Comment by szdavid92** [comment]
Yes, you are right, we need a combinator that given a combination of property lookups and bracketed forms can access the indexer. Maybe may old Scala code can be put to use.

**Comment by szdavid92** [comment]
I am talking about this: https://github.com/FTSRG/ingraph/tree/sre

**Comment by szdavid92** [comment]
Btw this railroad diagram hardly makes sense to me. Could you explain what does interleaving IS NULLs with []s mean?

```
x.name[0] IS NULL [1] IS NOT NULL [0]
```
It seems to be valid according to the railroad diagram I posted above.

**Comment by jmarton** [comment]
@szdavid92: there are expressions that could be valid according to the railroad diagrams, but not valid in openCypher. I think you have found such a case.
