### ISSUE TITLE
Fix resolution issues for projectList

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/ingraph#228]
Project class' projectList resolutions are NamedExpressions, but they really should be attributes. Or maybe :-).

lookup:
```
result = {Map$Map2@4660} "Map$Map2" size = 2
 0 = {Tuple2@6009} "(vertexattribute(segment, VertexLabelSet(Set(Segment),NonEmpty)),0)"
 1 = {Tuple2@6010} "('segment.length,1)"
```

projectList:
```
result = {ListBuffer@4725} "ListBuffer" size = 2
 0 = {UnresolvedAlias@5995} "unresolvedalias('segment, None)"
 1 = {Alias@5996} "'segment.length AS length#0"
```

**Comment by jmarton** [comment]
This has been done in 487dd1d0bb26d94606ab17e73d7d04b84a3be4bb, where projectList became `Seq[ReturnItem]`, where `ReturnItem.child` has a `toAttribute` method available. One #284 is merged, this will also be done.

**Comment by jmarton** [comment]
#284 was merged, so this is done.
