### ISSUE TITLE
Change ChangeSet data type to vector

### ISSUE THREAD

**Issue by hegyibalint** [FTSRG/ingraph#242]
Because of the too generic `Iterable[Tuple]`type, SortAndTopNode needs to cast the `changeSet` into a sortable type, which can get expensive. 
We use `Vector` in the [ChangeSet's constructor](https://github.com/FTSRG/ingraph/blob/master/ire/src/main/scala/hu/bme/mit/ire/messages/Messages.scala#L12) anyways, why not using the Vector as the type of the container?

**Comment by szarnyasg** [comment]
@wafle ?

**Comment by wafle** [comment]
I agree. Originally it was a Vector[Tuple]. I cannot find the article describing this, but you lose a lot of information about the characteristics of the data e.g. when you go [from set to tuple](https://github.com/FTSRG/ingraph/commit/8491e5f2e351700236fd22bcdb8d3084e6a3a782#diff-71c1b38869a507a7e0a94e1f21f3d1fdR41). Is it unique? What's the complexity for testing containment?

**Comment by szarnyasg** [comment]
@hegyibalint go ahead.
