### ISSUE TITLE
DELETE is broken

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/ingraph#291]
https://github.com/FTSRG/ingraph/blob/86b55c8281725f06932c3764cd75dffeee156c09/compiler/src/main/scala/ingraph/compiler/cypher2qplan/builders/CudBuilder.scala#L38

**Comment by jmarton** [comment]
@szarnyasg you probably meant

https://github.com/FTSRG/ingraph/blob/86b55c8281725f06932c3764cd75dffeee156c09/compiler/src/main/scala/ingraph/compiler/cypher2qplan/builders/CudBuilder.scala#L158-L159

**Comment by szarnyasg** [comment]
Yes, actually that's a different issue... :-)

**Comment by jmarton** [comment]
a996f4a35c5fa15730b7acdc996a7e178ec1fc3f intoduced a regression here :(
