### ISSUE TITLE
No edges in AllDifferent jnode

### ISSUE THREAD

**Issue by marci543** [FTSRG/ingraph#337]
In [TCK test: Get related to related to](https://github.com/FTSRG/ingraph/blob/472a91c79e87796c55f2444bde4b605c0c260a72/compiler/src/test/scala/ingraph/sandbox/TckCompilerTest.scala#L96) I would assume that `stages.jplan.child.child.edges` contains `_e0#0` and `_e1#0` edges, but the list is empty.
The same problem occurs too if the edges have names.

**Comment by jmarton** [comment]
Good point. Note that the edges list of the AllDifferent operator might also contain a reference to an edge list in case of a transitive expand (multi-hop edge pattern). For the particular matches to evaluate the AllDifferent predicate, edge lists need flattening.
