### ISSUE TITLE
Handle transitive closure operations

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/ingraph#34]
We should consider how to handle [minHops and maxHops]() in Cypher queries: https://neo4j.com/docs/developer-manual/current/cypher/#_variable_length_relationships

`-[:TYPE*minHops..maxHops]->`

The default values are:
* minHops: `1`
* maxHops: infinity

Possible cases (projections [π operator] omitted):
* If `maxHops` is limited: we should unfold the expression to a union of joins.
  * If `minHops` is 0 -> `e:E*0..2` can be defined as `r ∪ r ⨝ (E ∪ (E ⨝ E))`
  * If `minHops` is larger than 0 -> `e:E*1..3` can be defined as `r ⨝ (E ∪ (E ⨝ E) ∪ (E ⨝ E ⨝ E))`
* If `maxHops` is infinity (default):
  * If `minHops` is 0 -> `e:E*0..` can be defined as `r ∪ r ⨝ E+`
  * If `minHops` is 1 (default), we should simply use transitive closure -> `e:E*1..` can be defined as `r ⨝ E+`
  * If `minHops` is larger than 1 and `maxHops` is infinity, we should unfold exactly `minHops` hops -> `e:E*2..` can be defined as `r ⨝ E ⨝ E+`

**Comment by jmarton** [comment]
Related: #17

**Comment by szarnyasg** [comment]
Also related: 12e1fd7ce9a1f6bb24d1b713a40c1ac3c2dadaa9

**Comment by szarnyasg** [comment]
See the path semantics defined in: https://github.com/FTSRG/ingraph/blob/e4400092115503911176d1bcd86eb6bd4c7381b6/ingraph-relalg-model/src/main/resources/relalg.xcore#L583

**Comment by szarnyasg** [comment]
See also this paper: http://jackbergus.alwaysdata.net/paper_graph_graphq2017.pdf

**Comment by szarnyasg** [comment]
This needs to be tested thoroughly, but based a few simple tests, it works.
