### ISSUE TITLE
Support OPTIONAL MATCH as the first MATCH clause of a query

### ISSUE THREAD

**Issue by jmarton** [FTSRG/ingraph#40]
We should support single queries that has an `OPTIONAL MATCH` clause as their first `MATCH` clause.

E.g. the following should return a singlle `null`-row, provided, there is no vertex having the label `NON_EXISTENT_LABEL`.
```
OPTIONAL MATCH (n:NON_EXISTENT_LABEL)
RETURN n
```

Note: this implies that all `MATCH` clauses in this single query is `OPTIONAL MATCH`.

**Comment by szarnyasg** [comment]
As we discussed, one possible way to achieve is to use something similar to Oracle's [DUAL table](https://en.wikipedia.org/wiki/DUAL_table).
