### ISSUE TITLE
Enable regression testing by introducing two test sets

### ISSUE THREAD

**Issue by jmarton** [FTSRG/ingraph#41]
There are a few hundred tests that we have imported from several sources. Our project, however, is a work-in-progress and succeeds only for a subset of the tests. We would like to mark those tests that are known to work at some time point (test set 1). We require these tests to pass for future commits on Travis in order to recognize if something breaks.

To achieve this, we need to

- [x] mark tests that are required to pass (test set 1)
- [x] run test set 1 on Travis
- [x] create a convenient way to upgrade test set 1 from all tests with the newly covered tests

Note: test set 1 is intended to expand only, i.e. to form a set-series where each element is a superset of any previous elements.

**Comment by jmarton** [comment]
It is also an option that test set 1 and 2 complement each other, and eventually, test set 2 will become empty :slightly_smiling_face:

**Comment by szarnyasg** [comment]
Fixed with 42161c0bb2ddb6c81136a404a1ab0108c8c6287c, 64710cfaa7007de94b4f3307a48deaff2c87bbb3 and b8d7ec95457849daf31b512134f3bbda25b30c15.
