### ISSUE TITLE
How to handle "IS [NOT] NULL"

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/ingraph#42]
We currently have two enums for `IS_NULL`, `IS_NOT_NULL`: https://github.com/FTSRG/ingraph/blob/44e456d7f772b4cac446e9df8fcb7bd43a596b77/ingraph-relalg-xcore/src/relalg.xcore#L356

**Comment by jmarton** [comment]
Operators in the `UnaryNodeLogicalOperator` receive a single vertex or edge variable as its input and is currently used to express pattern constraints in the `openCypher` `WHERE` clause.

The traditional `UnaryLogicalOperator` operators are used for expressions that take a logical expression as its input, which, however, is uncapable to express `v.attr IS NULL`

There is a need to extend the latter, and there might be a common generalization for both cases.

**Comment by szarnyasg** [comment]
Let's continue this in #59
