### ISSUE TITLE
Implement SortAndTopNode operator for "ORDER BY ... SKIP/LIMIT ..." expressions

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/ingraph#56]
Implement a `SKIP`...`LIMIT` operator, which works on ordered expressions: https://neo4j.com/docs/developer-manual/current/cypher/#_skip_and_limit

We only support `SKIP` and `LIMIT` if they are preceded by an `ORDER BY` expression:
https://neo4j.com/docs/developer-manual/3.0/cypher/#query-order

> A sub-clause following RETURN or WITH, specifying that the output should be sorted in particular way.
The user of the library should specify a list of variable-direction pairs (e.g. person-ASC, city-DESC) for the  ordering.

**Comment by szarnyasg** [comment]
Issue #46 fixed, so we should be able to test the operator from integration tests.

**Comment by wafle** [comment]
Resolved via f378c9fcc551284f2ec925ba22d230b4c4e631cc.
