### ISSUE TITLE
UnaryLogicalOperatorType redesign

### ISSUE THREAD

**Issue by jmarton** [FTSRG/ingraph#59]
Currently, we have three operatorn in the `UnaryLogicalOperatorType` enum:

- `NOT`
- `IS_NULL`
- `IS_NOT_NULL`

Both of them has a logical value result. But `NOT` differs from `IS [NOT] NULL` in the sense that `NOT` operates on logical expressions (`UnaryLogicalExpression` is designed to accomodate this case), whereas `IS [NOT] NULL` is applicable to any expressions as well as to variables.

The representation of these expressions should be revisited, and possibly re-designed.

This is also a nice opportunity to revisit `UnaryNodeLogicalOperatorType` and `UnaryNodeLogicalExpression`, and come up with a more general idea.

**Comment by szarnyasg** [comment]
The migration to Catalyst makes this issue obsolete.
