### ISSUE TITLE
Support CASE clauses

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/ingraph#60]
Although CASE is not part of [standard Cypher](https://github.com/FTSRG/ingraph/blob/master/docs/standard-constructs-explained.md), we should support at least the [simple variant](https://github.com/FTSRG/ingraph/blob/master/docs/case.md). This is required by 3 of the [SNB Interactive queries](https://github.com/FTSRG/ingraph/tree/master/queries/ldbc-snb)

* [x] Add **Case Expression** to [`relalg.xcore`](https://github.com/FTSRG/ingraph/blob/83646ad12e874948158d984ed4a1c48038e9d3e5/ingraph-compiler/ingraph-compiler-relalg-model/src/main/resources/relalg.xcore#L501).
* [x] Add support for `CASE` to parser.
* [ ] Support `CASE` expressions in ire.

**Comment by szarnyasg** [comment]
We should check if the BI queries require this.

**Comment by szarnyasg** [comment]
It seems 1, 10, 22 and 25 might require `CASE`.

**Comment by szarnyasg** [comment]
Although not very difficult to implement, this is a non-standard construct, so closing this for now.

**Comment by jmarton** [comment]
In opencypher/openCypher#224, CASE became part of the standard constructs.

**Comment by szarnyasg** [comment]
Both the _simple_ and the _generic_ `CASE` are proposed in the related [CIR](https://github.com/opencypher/openCypher/issues/225).

**Comment by szarnyasg** [comment]
See also https://github.com/FTSRG/ingraph/blob/master/ingraph-compiler/ingraph-compiler-relalg-model/src/main/resources/relalg.xcore#L485

**Comment by jmarton** [comment]
@szarnyasg ire is the next step to do

**Comment by wafle** [comment]
I tried a couple of queries, they all run into a compiler crash:

```MATCH (n)
RETURN
CASE n.eyes
WHEN 'blue'
THEN 1
WHEN 'brown'
THEN 2
ELSE 3 END AS result```

```
fullName() method not implemented for class relalg.impl.SimpleCaseExpressionImpl
```

**Comment by szarnyasg** [comment]
It is now :-)... not the most elegant solution, but will work fine for most queries. Maybe it will work for all queries - I'll investigate this next week.

**Comment by szarnyasg** [comment]
I'll rename `GeneralCaseExpression` to `GenericCaseExpression`. (Sidenote: I should also rename `getAttributes` to something else, as it is not a getter).
