### ISSUE TITLE
Implement driver

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/ingraph#65]
Implement driver that allows the user to switch between a Neo4j server and an ingraph server.

Subtasks (from comment below by @imbur):

- [x] Implement client driver
- [ ] Implement middleware

**Comment by szarnyasg** [comment]
The most basic implementation looks something like https://github.com/FTSRG/ingraph/blob/c1024eef066490f3b0f34e195e97ac23f76e61f8/ingraph-driver/src/main/java/ingraph/driver/CypherDriverFactory.java

**Comment by imbur** [comment]
This task can be decomposed into two subtasks
- [ ] Implement client driver
- [ ] Implement middleware

**Comment by szarnyasg** [comment]
See the interfaces in the [`neo4j-reactive-driver` project](https://github.com/szarnyasg/neo4j-drivers): https://github.com/szarnyasg/neo4j-drivers/tree/master/neo4j-reactive-driver/src/main/java/neo4j/driver/reactive
