### ISSUE TITLE
How to introduce new variables with the projection operator

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/ingraph#77]
How should we handle tuples in cases when new variables are introduced as an expression? Example:

```
WITH 1 AS x, 2 AS y
RETURN x, 3 AS z
```

**Comment by jmarton** [comment]
What about our current approach, i.e. for the query

```cypher
WITH 1 AS x, 2 AS y
RETURN 3 AS z
```

we compile it to

![dual-projection](https://cloud.githubusercontent.com/assets/10688599/23333246/a3d15ff0-fb88-11e6-825c-05dc9fc6756f.png)

**Comment by szarnyasg** [comment]
This is fine so far, the problem arises when indexing the tuple. See the -1 values here: 

![image](https://cloud.githubusercontent.com/assets/1402801/23333298/ceb685aa-fb89-11e6-9326-106e585f9f06.png)

**Comment by szarnyasg** [comment]
See 255dfdb

**Comment by szarnyasg** [comment]
This is done, the rest of the work will be carried out in #110.
