### ISSUE TITLE
Start using branches and pull requests

### ISSUE THREAD

**Issue by wafle** [FTSRG/ingraph#84]
Would have prevented #83 or at least we would know which commit broke it.

**Comment by szarnyasg** [comment]
I fixed #83 in the meantime.

I agree, we should aim to keep the `master` branch to continuously "green", especially that the tech report is generated based on the its code (https://github.com/FTSRG/ingraph/blob/4b20270cd676450da73f930592a45ecf5f6583cb/.travis.yml#L36).
