### ISSUE TITLE
Handle Union in opencypher2relalg compilation

### ISSUE THREAD

**Issue by jmarton** [FTSRG/ingraph#9]
- [x] add Union as BetaOperator to EMF model
- [x] handle Union in cyp AST -> relalg compilation
- [x] use different VariableFactories fo each `singleQuery` (i.e. those that are unioned together)
- [x] make distinction between UNION ALL/UNION
  
  ```
  match (n:A)
  return n
  union
  match (n:D)
  return n
  ```
- [x] add requirement: variable aliases need to be matched (see also: #16)
  otherwise exception is thrown in Neo4j, see:
  
  ```
  CREATE (n1:A{name:"World"}) create (n2:B{whatever:"Universe"});
  MATCH (a:A) RETURN a AS a
  UNION
  MATCH (b:B) RETURN b AS a;
  ```
  
  `Neo4j: All sub queries in an UNION must have the same column names`

**Comment by jmarton** [comment]
Using different variablefactories for each singleQuery is done in commit 458f942a168720bc3d9a412444b5f127991dce12

**Comment by szarnyasg** [comment]
This does not work for some reason.

**Comment by jmarton** [comment]
@szarnyasg please give me a query leading to failing/erroneous compilation.

**Comment by szarnyasg** [comment]
Sorry, my mistake - all failing queries only had `RETURN` clauses (i.e. `RETURN ... UNION RETURN ...`), which is currently not supported.
