### ISSUE TITLE
Move ExpressionVariable TeX serialization methods to VariableConverter

### ISSUE THREAD

**Issue by jmarton** [FTSRG/ingraph#92]
Currently, TeX serialization of `ExpressionVariable` elements from the relalg instance model are implemented in `MiscConverters`. This should be moved to `VariableConverter` as it would be nicer.

**Edited:** Also affected: `VariableConverter.convertVariable(ExpressionVariable)`

**Comment by szarnyasg** [comment]
Oops. This caused some unexpected issues: 

![image](https://cloud.githubusercontent.com/assets/1402801/24587919/32c781d8-17bf-11e7-9d2f-eb42ad0ff013.png)
